name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    environment: stage
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd newtone-shop
            git pull origin master

            docker stop newtone-shop-app
            docker build -t newtone-shop .
            docker run -p 8080:80 --rm --name newtone-shop-app newtone-shop
